#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logat504
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Logat504")]
	public partial class LSC_504LogatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAzmoonLevel(tblAzmoonLevel instance);
    partial void UpdatetblAzmoonLevel(tblAzmoonLevel instance);
    partial void DeletetblAzmoonLevel(tblAzmoonLevel instance);
    partial void InserttblUserType(tblUserType instance);
    partial void UpdatetblUserType(tblUserType instance);
    partial void DeletetblUserType(tblUserType instance);
    partial void InserttblAzmoonNatijeh(tblAzmoonNatijeh instance);
    partial void UpdatetblAzmoonNatijeh(tblAzmoonNatijeh instance);
    partial void DeletetblAzmoonNatijeh(tblAzmoonNatijeh instance);
    partial void InserttblAzmoonSoalat(tblAzmoonSoalat instance);
    partial void UpdatetblAzmoonSoalat(tblAzmoonSoalat instance);
    partial void DeletetblAzmoonSoalat(tblAzmoonSoalat instance);
    partial void InserttblAzmoonTitle(tblAzmoonTitle instance);
    partial void UpdatetblAzmoonTitle(tblAzmoonTitle instance);
    partial void DeletetblAzmoonTitle(tblAzmoonTitle instance);
    partial void InserttblLoghatHa(tblLoghatHa instance);
    partial void UpdatetblLoghatHa(tblLoghatHa instance);
    partial void DeletetblLoghatHa(tblLoghatHa instance);
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    #endregion
		
		public LSC_504LogatDataContext() : 
				base(global::Logat504.Properties.Settings.Default.Logat504ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LSC_504LogatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LSC_504LogatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LSC_504LogatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LSC_504LogatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAzmoonLevel> tblAzmoonLevels
		{
			get
			{
				return this.GetTable<tblAzmoonLevel>();
			}
		}
		
		public System.Data.Linq.Table<tblUserType> tblUserTypes
		{
			get
			{
				return this.GetTable<tblUserType>();
			}
		}
		
		public System.Data.Linq.Table<tblAzmoonNatijeh> tblAzmoonNatijehs
		{
			get
			{
				return this.GetTable<tblAzmoonNatijeh>();
			}
		}
		
		public System.Data.Linq.Table<tblAzmoonSoalat> tblAzmoonSoalats
		{
			get
			{
				return this.GetTable<tblAzmoonSoalat>();
			}
		}
		
		public System.Data.Linq.Table<tblAzmoonTitle> tblAzmoonTitles
		{
			get
			{
				return this.GetTable<tblAzmoonTitle>();
			}
		}
		
		public System.Data.Linq.Table<tblLoghatHa> tblLoghatHas
		{
			get
			{
				return this.GetTable<tblLoghatHa>();
			}
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<xtblAzmoonTitle> xtblAzmoonTitles
		{
			get
			{
				return this.GetTable<xtblAzmoonTitle>();
			}
		}
		
		public System.Data.Linq.Table<xtblViewMark> xtblViewMarks
		{
			get
			{
				return this.GetTable<xtblViewMark>();
			}
		}
		
		public System.Data.Linq.Table<xtblDropUser> xtblDropUsers
		{
			get
			{
				return this.GetTable<xtblDropUser>();
			}
		}
		
		public System.Data.Linq.Table<xtblKarname> xtblKarnames
		{
			get
			{
				return this.GetTable<xtblKarname>();
			}
		}
		
		public System.Data.Linq.Table<xtblAvgKarname> xtblAvgKarnames
		{
			get
			{
				return this.GetTable<xtblAvgKarname>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAzmoonLevels")]
	public partial class tblAzmoonLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AzmoonLevelID;
		
		private string _AzmoonLevelDescription;
		
		private EntitySet<tblAzmoonTitle> _tblAzmoonTitles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAzmoonLevelIDChanging(int value);
    partial void OnAzmoonLevelIDChanged();
    partial void OnAzmoonLevelDescriptionChanging(string value);
    partial void OnAzmoonLevelDescriptionChanged();
    #endregion
		
		public tblAzmoonLevel()
		{
			this._tblAzmoonTitles = new EntitySet<tblAzmoonTitle>(new Action<tblAzmoonTitle>(this.attach_tblAzmoonTitles), new Action<tblAzmoonTitle>(this.detach_tblAzmoonTitles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonLevelID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AzmoonLevelID
		{
			get
			{
				return this._AzmoonLevelID;
			}
			set
			{
				if ((this._AzmoonLevelID != value))
				{
					this.OnAzmoonLevelIDChanging(value);
					this.SendPropertyChanging();
					this._AzmoonLevelID = value;
					this.SendPropertyChanged("AzmoonLevelID");
					this.OnAzmoonLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonLevelDescription", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AzmoonLevelDescription
		{
			get
			{
				return this._AzmoonLevelDescription;
			}
			set
			{
				if ((this._AzmoonLevelDescription != value))
				{
					this.OnAzmoonLevelDescriptionChanging(value);
					this.SendPropertyChanging();
					this._AzmoonLevelDescription = value;
					this.SendPropertyChanged("AzmoonLevelDescription");
					this.OnAzmoonLevelDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAzmoonLevel_tblAzmoonTitle", Storage="_tblAzmoonTitles", ThisKey="AzmoonLevelID", OtherKey="AzmoonLevelID")]
		public EntitySet<tblAzmoonTitle> tblAzmoonTitles
		{
			get
			{
				return this._tblAzmoonTitles;
			}
			set
			{
				this._tblAzmoonTitles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblAzmoonTitles(tblAzmoonTitle entity)
		{
			this.SendPropertyChanging();
			entity.tblAzmoonLevel = this;
		}
		
		private void detach_tblAzmoonTitles(tblAzmoonTitle entity)
		{
			this.SendPropertyChanging();
			entity.tblAzmoonLevel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUserTypes")]
	public partial class tblUserType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserTypeID;
		
		private string _UserTypeDescription;
		
		private EntitySet<tblUser> _tblUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserTypeIDChanging(int value);
    partial void OnUserTypeIDChanged();
    partial void OnUserTypeDescriptionChanging(string value);
    partial void OnUserTypeDescriptionChanged();
    #endregion
		
		public tblUserType()
		{
			this._tblUsers = new EntitySet<tblUser>(new Action<tblUser>(this.attach_tblUsers), new Action<tblUser>(this.detach_tblUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserTypeID
		{
			get
			{
				return this._UserTypeID;
			}
			set
			{
				if ((this._UserTypeID != value))
				{
					this.OnUserTypeIDChanging(value);
					this.SendPropertyChanging();
					this._UserTypeID = value;
					this.SendPropertyChanged("UserTypeID");
					this.OnUserTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTypeDescription", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserTypeDescription
		{
			get
			{
				return this._UserTypeDescription;
			}
			set
			{
				if ((this._UserTypeDescription != value))
				{
					this.OnUserTypeDescriptionChanging(value);
					this.SendPropertyChanging();
					this._UserTypeDescription = value;
					this.SendPropertyChanged("UserTypeDescription");
					this.OnUserTypeDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUserType_tblUser", Storage="_tblUsers", ThisKey="UserTypeID", OtherKey="UserTypeID")]
		public EntitySet<tblUser> tblUsers
		{
			get
			{
				return this._tblUsers;
			}
			set
			{
				this._tblUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUsers(tblUser entity)
		{
			this.SendPropertyChanging();
			entity.tblUserType = this;
		}
		
		private void detach_tblUsers(tblUser entity)
		{
			this.SendPropertyChanging();
			entity.tblUserType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAzmoonNatijeh")]
	public partial class tblAzmoonNatijeh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _NatijehID;
		
		private decimal _AzmoonTitleID;
		
		private string _UserNAme;
		
		private string _AzmoonDate;
		
		private int _SoalateSahih;
		
		private int _SoalateEshtebah;
		
		private int _BedooneJavab;
		
		private double _TotalMark;
		
		private EntityRef<tblAzmoonTitle> _tblAzmoonTitle;
		
		private EntityRef<tblUser> _tblUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNatijehIDChanging(decimal value);
    partial void OnNatijehIDChanged();
    partial void OnAzmoonTitleIDChanging(decimal value);
    partial void OnAzmoonTitleIDChanged();
    partial void OnUserNAmeChanging(string value);
    partial void OnUserNAmeChanged();
    partial void OnAzmoonDateChanging(string value);
    partial void OnAzmoonDateChanged();
    partial void OnSoalateSahihChanging(int value);
    partial void OnSoalateSahihChanged();
    partial void OnSoalateEshtebahChanging(int value);
    partial void OnSoalateEshtebahChanged();
    partial void OnBedooneJavabChanging(int value);
    partial void OnBedooneJavabChanged();
    partial void OnTotalMarkChanging(double value);
    partial void OnTotalMarkChanged();
    #endregion
		
		public tblAzmoonNatijeh()
		{
			this._tblAzmoonTitle = default(EntityRef<tblAzmoonTitle>);
			this._tblUser = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NatijehID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal NatijehID
		{
			get
			{
				return this._NatijehID;
			}
			set
			{
				if ((this._NatijehID != value))
				{
					this.OnNatijehIDChanging(value);
					this.SendPropertyChanging();
					this._NatijehID = value;
					this.SendPropertyChanged("NatijehID");
					this.OnNatijehIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonTitleID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal AzmoonTitleID
		{
			get
			{
				return this._AzmoonTitleID;
			}
			set
			{
				if ((this._AzmoonTitleID != value))
				{
					if (this._tblAzmoonTitle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAzmoonTitleIDChanging(value);
					this.SendPropertyChanging();
					this._AzmoonTitleID = value;
					this.SendPropertyChanged("AzmoonTitleID");
					this.OnAzmoonTitleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNAme", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserNAme
		{
			get
			{
				return this._UserNAme;
			}
			set
			{
				if ((this._UserNAme != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNAmeChanging(value);
					this.SendPropertyChanging();
					this._UserNAme = value;
					this.SendPropertyChanged("UserNAme");
					this.OnUserNAmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AzmoonDate
		{
			get
			{
				return this._AzmoonDate;
			}
			set
			{
				if ((this._AzmoonDate != value))
				{
					this.OnAzmoonDateChanging(value);
					this.SendPropertyChanging();
					this._AzmoonDate = value;
					this.SendPropertyChanged("AzmoonDate");
					this.OnAzmoonDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoalateSahih", DbType="Int NOT NULL")]
		public int SoalateSahih
		{
			get
			{
				return this._SoalateSahih;
			}
			set
			{
				if ((this._SoalateSahih != value))
				{
					this.OnSoalateSahihChanging(value);
					this.SendPropertyChanging();
					this._SoalateSahih = value;
					this.SendPropertyChanged("SoalateSahih");
					this.OnSoalateSahihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoalateEshtebah", DbType="Int NOT NULL")]
		public int SoalateEshtebah
		{
			get
			{
				return this._SoalateEshtebah;
			}
			set
			{
				if ((this._SoalateEshtebah != value))
				{
					this.OnSoalateEshtebahChanging(value);
					this.SendPropertyChanging();
					this._SoalateEshtebah = value;
					this.SendPropertyChanged("SoalateEshtebah");
					this.OnSoalateEshtebahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedooneJavab", DbType="Int NOT NULL")]
		public int BedooneJavab
		{
			get
			{
				return this._BedooneJavab;
			}
			set
			{
				if ((this._BedooneJavab != value))
				{
					this.OnBedooneJavabChanging(value);
					this.SendPropertyChanging();
					this._BedooneJavab = value;
					this.SendPropertyChanged("BedooneJavab");
					this.OnBedooneJavabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMark", DbType="Float NOT NULL")]
		public double TotalMark
		{
			get
			{
				return this._TotalMark;
			}
			set
			{
				if ((this._TotalMark != value))
				{
					this.OnTotalMarkChanging(value);
					this.SendPropertyChanging();
					this._TotalMark = value;
					this.SendPropertyChanged("TotalMark");
					this.OnTotalMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAzmoonTitle_tblAzmoonNatijeh", Storage="_tblAzmoonTitle", ThisKey="AzmoonTitleID", OtherKey="AzmoonID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblAzmoonTitle tblAzmoonTitle
		{
			get
			{
				return this._tblAzmoonTitle.Entity;
			}
			set
			{
				tblAzmoonTitle previousValue = this._tblAzmoonTitle.Entity;
				if (((previousValue != value) 
							|| (this._tblAzmoonTitle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAzmoonTitle.Entity = null;
						previousValue.tblAzmoonNatijehs.Remove(this);
					}
					this._tblAzmoonTitle.Entity = value;
					if ((value != null))
					{
						value.tblAzmoonNatijehs.Add(this);
						this._AzmoonTitleID = value.AzmoonID;
					}
					else
					{
						this._AzmoonTitleID = default(decimal);
					}
					this.SendPropertyChanged("tblAzmoonTitle");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblAzmoonNatijeh", Storage="_tblUser", ThisKey="UserNAme", OtherKey="UserNAme", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblAzmoonNatijehs.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblAzmoonNatijehs.Add(this);
						this._UserNAme = value.UserNAme;
					}
					else
					{
						this._UserNAme = default(string);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAzmoonSoalat")]
	public partial class tblAzmoonSoalat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _SoalID;
		
		private decimal _AzmoonTitleID;
		
		private string _SoAlDescription;
		
		private string _Gozineie1;
		
		private string _Gozineie2;
		
		private string _Gozineie3;
		
		private string _Gozineie4;
		
		private int _GozineieSahih;
		
		private EntityRef<tblAzmoonTitle> _tblAzmoonTitle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoalIDChanging(decimal value);
    partial void OnSoalIDChanged();
    partial void OnAzmoonTitleIDChanging(decimal value);
    partial void OnAzmoonTitleIDChanged();
    partial void OnSoAlDescriptionChanging(string value);
    partial void OnSoAlDescriptionChanged();
    partial void OnGozineie1Changing(string value);
    partial void OnGozineie1Changed();
    partial void OnGozineie2Changing(string value);
    partial void OnGozineie2Changed();
    partial void OnGozineie3Changing(string value);
    partial void OnGozineie3Changed();
    partial void OnGozineie4Changing(string value);
    partial void OnGozineie4Changed();
    partial void OnGozineieSahihChanging(int value);
    partial void OnGozineieSahihChanged();
    #endregion
		
		public tblAzmoonSoalat()
		{
			this._tblAzmoonTitle = default(EntityRef<tblAzmoonTitle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoalID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal SoalID
		{
			get
			{
				return this._SoalID;
			}
			set
			{
				if ((this._SoalID != value))
				{
					this.OnSoalIDChanging(value);
					this.SendPropertyChanging();
					this._SoalID = value;
					this.SendPropertyChanged("SoalID");
					this.OnSoalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonTitleID", DbType="Decimal(18,0) NOT NULL")]
		public decimal AzmoonTitleID
		{
			get
			{
				return this._AzmoonTitleID;
			}
			set
			{
				if ((this._AzmoonTitleID != value))
				{
					if (this._tblAzmoonTitle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAzmoonTitleIDChanging(value);
					this.SendPropertyChanging();
					this._AzmoonTitleID = value;
					this.SendPropertyChanged("AzmoonTitleID");
					this.OnAzmoonTitleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoAlDescription", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string SoAlDescription
		{
			get
			{
				return this._SoAlDescription;
			}
			set
			{
				if ((this._SoAlDescription != value))
				{
					this.OnSoAlDescriptionChanging(value);
					this.SendPropertyChanging();
					this._SoAlDescription = value;
					this.SendPropertyChanged("SoAlDescription");
					this.OnSoAlDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gozineie1", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Gozineie1
		{
			get
			{
				return this._Gozineie1;
			}
			set
			{
				if ((this._Gozineie1 != value))
				{
					this.OnGozineie1Changing(value);
					this.SendPropertyChanging();
					this._Gozineie1 = value;
					this.SendPropertyChanged("Gozineie1");
					this.OnGozineie1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gozineie2", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Gozineie2
		{
			get
			{
				return this._Gozineie2;
			}
			set
			{
				if ((this._Gozineie2 != value))
				{
					this.OnGozineie2Changing(value);
					this.SendPropertyChanging();
					this._Gozineie2 = value;
					this.SendPropertyChanged("Gozineie2");
					this.OnGozineie2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gozineie3", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Gozineie3
		{
			get
			{
				return this._Gozineie3;
			}
			set
			{
				if ((this._Gozineie3 != value))
				{
					this.OnGozineie3Changing(value);
					this.SendPropertyChanging();
					this._Gozineie3 = value;
					this.SendPropertyChanged("Gozineie3");
					this.OnGozineie3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gozineie4", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Gozineie4
		{
			get
			{
				return this._Gozineie4;
			}
			set
			{
				if ((this._Gozineie4 != value))
				{
					this.OnGozineie4Changing(value);
					this.SendPropertyChanging();
					this._Gozineie4 = value;
					this.SendPropertyChanged("Gozineie4");
					this.OnGozineie4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GozineieSahih", DbType="Int NOT NULL")]
		public int GozineieSahih
		{
			get
			{
				return this._GozineieSahih;
			}
			set
			{
				if ((this._GozineieSahih != value))
				{
					this.OnGozineieSahihChanging(value);
					this.SendPropertyChanging();
					this._GozineieSahih = value;
					this.SendPropertyChanged("GozineieSahih");
					this.OnGozineieSahihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAzmoonTitle_tblAzmoonSoalat", Storage="_tblAzmoonTitle", ThisKey="AzmoonTitleID", OtherKey="AzmoonID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblAzmoonTitle tblAzmoonTitle
		{
			get
			{
				return this._tblAzmoonTitle.Entity;
			}
			set
			{
				tblAzmoonTitle previousValue = this._tblAzmoonTitle.Entity;
				if (((previousValue != value) 
							|| (this._tblAzmoonTitle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAzmoonTitle.Entity = null;
						previousValue.tblAzmoonSoalats.Remove(this);
					}
					this._tblAzmoonTitle.Entity = value;
					if ((value != null))
					{
						value.tblAzmoonSoalats.Add(this);
						this._AzmoonTitleID = value.AzmoonID;
					}
					else
					{
						this._AzmoonTitleID = default(decimal);
					}
					this.SendPropertyChanged("tblAzmoonTitle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAzmoonTitle")]
	public partial class tblAzmoonTitle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _AzmoonID;
		
		private int _AzmoonLevelID;
		
		private string _AzmoonTitle;
		
		private string _AzmoonReading;
		
		private EntitySet<tblAzmoonNatijeh> _tblAzmoonNatijehs;
		
		private EntitySet<tblAzmoonSoalat> _tblAzmoonSoalats;
		
		private EntityRef<tblAzmoonLevel> _tblAzmoonLevel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAzmoonIDChanging(decimal value);
    partial void OnAzmoonIDChanged();
    partial void OnAzmoonLevelIDChanging(int value);
    partial void OnAzmoonLevelIDChanged();
    partial void OnAzmoonTitleChanging(string value);
    partial void OnAzmoonTitleChanged();
    partial void OnAzmoonReadingChanging(string value);
    partial void OnAzmoonReadingChanged();
    #endregion
		
		public tblAzmoonTitle()
		{
			this._tblAzmoonNatijehs = new EntitySet<tblAzmoonNatijeh>(new Action<tblAzmoonNatijeh>(this.attach_tblAzmoonNatijehs), new Action<tblAzmoonNatijeh>(this.detach_tblAzmoonNatijehs));
			this._tblAzmoonSoalats = new EntitySet<tblAzmoonSoalat>(new Action<tblAzmoonSoalat>(this.attach_tblAzmoonSoalats), new Action<tblAzmoonSoalat>(this.detach_tblAzmoonSoalats));
			this._tblAzmoonLevel = default(EntityRef<tblAzmoonLevel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal AzmoonID
		{
			get
			{
				return this._AzmoonID;
			}
			set
			{
				if ((this._AzmoonID != value))
				{
					this.OnAzmoonIDChanging(value);
					this.SendPropertyChanging();
					this._AzmoonID = value;
					this.SendPropertyChanged("AzmoonID");
					this.OnAzmoonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonLevelID", DbType="Int NOT NULL")]
		public int AzmoonLevelID
		{
			get
			{
				return this._AzmoonLevelID;
			}
			set
			{
				if ((this._AzmoonLevelID != value))
				{
					if (this._tblAzmoonLevel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAzmoonLevelIDChanging(value);
					this.SendPropertyChanging();
					this._AzmoonLevelID = value;
					this.SendPropertyChanged("AzmoonLevelID");
					this.OnAzmoonLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AzmoonTitle
		{
			get
			{
				return this._AzmoonTitle;
			}
			set
			{
				if ((this._AzmoonTitle != value))
				{
					this.OnAzmoonTitleChanging(value);
					this.SendPropertyChanging();
					this._AzmoonTitle = value;
					this.SendPropertyChanged("AzmoonTitle");
					this.OnAzmoonTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonReading", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string AzmoonReading
		{
			get
			{
				return this._AzmoonReading;
			}
			set
			{
				if ((this._AzmoonReading != value))
				{
					this.OnAzmoonReadingChanging(value);
					this.SendPropertyChanging();
					this._AzmoonReading = value;
					this.SendPropertyChanged("AzmoonReading");
					this.OnAzmoonReadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAzmoonTitle_tblAzmoonNatijeh", Storage="_tblAzmoonNatijehs", ThisKey="AzmoonID", OtherKey="AzmoonTitleID")]
		public EntitySet<tblAzmoonNatijeh> tblAzmoonNatijehs
		{
			get
			{
				return this._tblAzmoonNatijehs;
			}
			set
			{
				this._tblAzmoonNatijehs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAzmoonTitle_tblAzmoonSoalat", Storage="_tblAzmoonSoalats", ThisKey="AzmoonID", OtherKey="AzmoonTitleID")]
		public EntitySet<tblAzmoonSoalat> tblAzmoonSoalats
		{
			get
			{
				return this._tblAzmoonSoalats;
			}
			set
			{
				this._tblAzmoonSoalats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAzmoonLevel_tblAzmoonTitle", Storage="_tblAzmoonLevel", ThisKey="AzmoonLevelID", OtherKey="AzmoonLevelID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblAzmoonLevel tblAzmoonLevel
		{
			get
			{
				return this._tblAzmoonLevel.Entity;
			}
			set
			{
				tblAzmoonLevel previousValue = this._tblAzmoonLevel.Entity;
				if (((previousValue != value) 
							|| (this._tblAzmoonLevel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAzmoonLevel.Entity = null;
						previousValue.tblAzmoonTitles.Remove(this);
					}
					this._tblAzmoonLevel.Entity = value;
					if ((value != null))
					{
						value.tblAzmoonTitles.Add(this);
						this._AzmoonLevelID = value.AzmoonLevelID;
					}
					else
					{
						this._AzmoonLevelID = default(int);
					}
					this.SendPropertyChanged("tblAzmoonLevel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblAzmoonNatijehs(tblAzmoonNatijeh entity)
		{
			this.SendPropertyChanging();
			entity.tblAzmoonTitle = this;
		}
		
		private void detach_tblAzmoonNatijehs(tblAzmoonNatijeh entity)
		{
			this.SendPropertyChanging();
			entity.tblAzmoonTitle = null;
		}
		
		private void attach_tblAzmoonSoalats(tblAzmoonSoalat entity)
		{
			this.SendPropertyChanging();
			entity.tblAzmoonTitle = this;
		}
		
		private void detach_tblAzmoonSoalats(tblAzmoonSoalat entity)
		{
			this.SendPropertyChanging();
			entity.tblAzmoonTitle = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoghatHa")]
	public partial class tblLoghatHa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _LogatID;
		
		private string _LogatEnglish;
		
		private string _LoghatFarsi;
		
		private string _LoghatMotaradef;
		
		private string _LogatSaier;
		
		private string _DateOfAdd;
		
		private string _AdderUserName;
		
		private EntityRef<tblUser> _tblUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogatIDChanging(decimal value);
    partial void OnLogatIDChanged();
    partial void OnLogatEnglishChanging(string value);
    partial void OnLogatEnglishChanged();
    partial void OnLoghatFarsiChanging(string value);
    partial void OnLoghatFarsiChanged();
    partial void OnLoghatMotaradefChanging(string value);
    partial void OnLoghatMotaradefChanged();
    partial void OnLogatSaierChanging(string value);
    partial void OnLogatSaierChanged();
    partial void OnDateOfAddChanging(string value);
    partial void OnDateOfAddChanged();
    partial void OnAdderUserNameChanging(string value);
    partial void OnAdderUserNameChanged();
    #endregion
		
		public tblLoghatHa()
		{
			this._tblUser = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogatID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal LogatID
		{
			get
			{
				return this._LogatID;
			}
			set
			{
				if ((this._LogatID != value))
				{
					this.OnLogatIDChanging(value);
					this.SendPropertyChanging();
					this._LogatID = value;
					this.SendPropertyChanged("LogatID");
					this.OnLogatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogatEnglish", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LogatEnglish
		{
			get
			{
				return this._LogatEnglish;
			}
			set
			{
				if ((this._LogatEnglish != value))
				{
					this.OnLogatEnglishChanging(value);
					this.SendPropertyChanging();
					this._LogatEnglish = value;
					this.SendPropertyChanged("LogatEnglish");
					this.OnLogatEnglishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoghatFarsi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string LoghatFarsi
		{
			get
			{
				return this._LoghatFarsi;
			}
			set
			{
				if ((this._LoghatFarsi != value))
				{
					this.OnLoghatFarsiChanging(value);
					this.SendPropertyChanging();
					this._LoghatFarsi = value;
					this.SendPropertyChanged("LoghatFarsi");
					this.OnLoghatFarsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoghatMotaradef", DbType="NVarChar(350) NOT NULL", CanBeNull=false)]
		public string LoghatMotaradef
		{
			get
			{
				return this._LoghatMotaradef;
			}
			set
			{
				if ((this._LoghatMotaradef != value))
				{
					this.OnLoghatMotaradefChanging(value);
					this.SendPropertyChanging();
					this._LoghatMotaradef = value;
					this.SendPropertyChanged("LoghatMotaradef");
					this.OnLoghatMotaradefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogatSaier", DbType="NVarChar(350) NOT NULL", CanBeNull=false)]
		public string LogatSaier
		{
			get
			{
				return this._LogatSaier;
			}
			set
			{
				if ((this._LogatSaier != value))
				{
					this.OnLogatSaierChanging(value);
					this.SendPropertyChanging();
					this._LogatSaier = value;
					this.SendPropertyChanged("LogatSaier");
					this.OnLogatSaierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfAdd", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DateOfAdd
		{
			get
			{
				return this._DateOfAdd;
			}
			set
			{
				if ((this._DateOfAdd != value))
				{
					this.OnDateOfAddChanging(value);
					this.SendPropertyChanging();
					this._DateOfAdd = value;
					this.SendPropertyChanged("DateOfAdd");
					this.OnDateOfAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdderUserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AdderUserName
		{
			get
			{
				return this._AdderUserName;
			}
			set
			{
				if ((this._AdderUserName != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdderUserNameChanging(value);
					this.SendPropertyChanging();
					this._AdderUserName = value;
					this.SendPropertyChanged("AdderUserName");
					this.OnAdderUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblLoghatHa", Storage="_tblUser", ThisKey="AdderUserName", OtherKey="UserNAme", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblLoghatHas.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblLoghatHas.Add(this);
						this._AdderUserName = value.UserNAme;
					}
					else
					{
						this._AdderUserName = default(string);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsers")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _UsersID;
		
		private string _UserNAme;
		
		private string _UserPWA;
		
		private System.Nullable<int> _UserTypeID;
		
		private string _NameOfUsr;
		
		private string _SNameOfUsr;
		
		private string _MobilePhone;
		
		private string _EmailOfUser;
		
		private EntitySet<tblAzmoonNatijeh> _tblAzmoonNatijehs;
		
		private EntitySet<tblLoghatHa> _tblLoghatHas;
		
		private EntityRef<tblUserType> _tblUserType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsersIDChanging(decimal value);
    partial void OnUsersIDChanged();
    partial void OnUserNAmeChanging(string value);
    partial void OnUserNAmeChanged();
    partial void OnUserPWAChanging(string value);
    partial void OnUserPWAChanged();
    partial void OnUserTypeIDChanging(System.Nullable<int> value);
    partial void OnUserTypeIDChanged();
    partial void OnNameOfUsrChanging(string value);
    partial void OnNameOfUsrChanged();
    partial void OnSNameOfUsrChanging(string value);
    partial void OnSNameOfUsrChanged();
    partial void OnMobilePhoneChanging(string value);
    partial void OnMobilePhoneChanged();
    partial void OnEmailOfUserChanging(string value);
    partial void OnEmailOfUserChanged();
    #endregion
		
		public tblUser()
		{
			this._tblAzmoonNatijehs = new EntitySet<tblAzmoonNatijeh>(new Action<tblAzmoonNatijeh>(this.attach_tblAzmoonNatijehs), new Action<tblAzmoonNatijeh>(this.detach_tblAzmoonNatijehs));
			this._tblLoghatHas = new EntitySet<tblLoghatHa>(new Action<tblLoghatHa>(this.attach_tblLoghatHas), new Action<tblLoghatHa>(this.detach_tblLoghatHas));
			this._tblUserType = default(EntityRef<tblUserType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal UsersID
		{
			get
			{
				return this._UsersID;
			}
			set
			{
				if ((this._UsersID != value))
				{
					this.OnUsersIDChanging(value);
					this.SendPropertyChanging();
					this._UsersID = value;
					this.SendPropertyChanged("UsersID");
					this.OnUsersIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNAme", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserNAme
		{
			get
			{
				return this._UserNAme;
			}
			set
			{
				if ((this._UserNAme != value))
				{
					this.OnUserNAmeChanging(value);
					this.SendPropertyChanging();
					this._UserNAme = value;
					this.SendPropertyChanged("UserNAme");
					this.OnUserNAmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPWA", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserPWA
		{
			get
			{
				return this._UserPWA;
			}
			set
			{
				if ((this._UserPWA != value))
				{
					this.OnUserPWAChanging(value);
					this.SendPropertyChanging();
					this._UserPWA = value;
					this.SendPropertyChanged("UserPWA");
					this.OnUserPWAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTypeID", DbType="Int")]
		public System.Nullable<int> UserTypeID
		{
			get
			{
				return this._UserTypeID;
			}
			set
			{
				if ((this._UserTypeID != value))
				{
					if (this._tblUserType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserTypeIDChanging(value);
					this.SendPropertyChanging();
					this._UserTypeID = value;
					this.SendPropertyChanged("UserTypeID");
					this.OnUserTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOfUsr", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NameOfUsr
		{
			get
			{
				return this._NameOfUsr;
			}
			set
			{
				if ((this._NameOfUsr != value))
				{
					this.OnNameOfUsrChanging(value);
					this.SendPropertyChanging();
					this._NameOfUsr = value;
					this.SendPropertyChanged("NameOfUsr");
					this.OnNameOfUsrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNameOfUsr", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SNameOfUsr
		{
			get
			{
				return this._SNameOfUsr;
			}
			set
			{
				if ((this._SNameOfUsr != value))
				{
					this.OnSNameOfUsrChanging(value);
					this.SendPropertyChanging();
					this._SNameOfUsr = value;
					this.SendPropertyChanged("SNameOfUsr");
					this.OnSNameOfUsrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePhone", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string MobilePhone
		{
			get
			{
				return this._MobilePhone;
			}
			set
			{
				if ((this._MobilePhone != value))
				{
					this.OnMobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._MobilePhone = value;
					this.SendPropertyChanged("MobilePhone");
					this.OnMobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailOfUser", DbType="NVarChar(250)")]
		public string EmailOfUser
		{
			get
			{
				return this._EmailOfUser;
			}
			set
			{
				if ((this._EmailOfUser != value))
				{
					this.OnEmailOfUserChanging(value);
					this.SendPropertyChanging();
					this._EmailOfUser = value;
					this.SendPropertyChanged("EmailOfUser");
					this.OnEmailOfUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblAzmoonNatijeh", Storage="_tblAzmoonNatijehs", ThisKey="UserNAme", OtherKey="UserNAme")]
		public EntitySet<tblAzmoonNatijeh> tblAzmoonNatijehs
		{
			get
			{
				return this._tblAzmoonNatijehs;
			}
			set
			{
				this._tblAzmoonNatijehs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblLoghatHa", Storage="_tblLoghatHas", ThisKey="UserNAme", OtherKey="AdderUserName")]
		public EntitySet<tblLoghatHa> tblLoghatHas
		{
			get
			{
				return this._tblLoghatHas;
			}
			set
			{
				this._tblLoghatHas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUserType_tblUser", Storage="_tblUserType", ThisKey="UserTypeID", OtherKey="UserTypeID", IsForeignKey=true)]
		public tblUserType tblUserType
		{
			get
			{
				return this._tblUserType.Entity;
			}
			set
			{
				tblUserType previousValue = this._tblUserType.Entity;
				if (((previousValue != value) 
							|| (this._tblUserType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUserType.Entity = null;
						previousValue.tblUsers.Remove(this);
					}
					this._tblUserType.Entity = value;
					if ((value != null))
					{
						value.tblUsers.Add(this);
						this._UserTypeID = value.UserTypeID;
					}
					else
					{
						this._UserTypeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUserType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblAzmoonNatijehs(tblAzmoonNatijeh entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblAzmoonNatijehs(tblAzmoonNatijeh entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
		
		private void attach_tblLoghatHas(tblLoghatHa entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblLoghatHas(tblLoghatHa entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xtblAzmoonTitles")]
	public partial class xtblAzmoonTitle
	{
		
		private decimal _AzmoonID;
		
		private string _Expr1;
		
		private int _AzmoonLevelID;
		
		public xtblAzmoonTitle()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonID", DbType="Decimal(18,0) NOT NULL")]
		public decimal AzmoonID
		{
			get
			{
				return this._AzmoonID;
			}
			set
			{
				if ((this._AzmoonID != value))
				{
					this._AzmoonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="NVarChar(327) NOT NULL", CanBeNull=false)]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonLevelID", DbType="Int NOT NULL")]
		public int AzmoonLevelID
		{
			get
			{
				return this._AzmoonLevelID;
			}
			set
			{
				if ((this._AzmoonLevelID != value))
				{
					this._AzmoonLevelID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xtblViewMarks")]
	public partial class xtblViewMark
	{
		
		private string _UserNAme;
		
		private string _NameOfUsr;
		
		private string _SNameOfUsr;
		
		private string _AzmoonTitle;
		
		private string _AzmoonDate;
		
		private int _SoalateSahih;
		
		private int _SoalateEshtebah;
		
		private int _BedooneJavab;
		
		private double _TotalMark;
		
		public xtblViewMark()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNAme", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserNAme
		{
			get
			{
				return this._UserNAme;
			}
			set
			{
				if ((this._UserNAme != value))
				{
					this._UserNAme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOfUsr", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NameOfUsr
		{
			get
			{
				return this._NameOfUsr;
			}
			set
			{
				if ((this._NameOfUsr != value))
				{
					this._NameOfUsr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNameOfUsr", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SNameOfUsr
		{
			get
			{
				return this._SNameOfUsr;
			}
			set
			{
				if ((this._SNameOfUsr != value))
				{
					this._SNameOfUsr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AzmoonTitle
		{
			get
			{
				return this._AzmoonTitle;
			}
			set
			{
				if ((this._AzmoonTitle != value))
				{
					this._AzmoonTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AzmoonDate
		{
			get
			{
				return this._AzmoonDate;
			}
			set
			{
				if ((this._AzmoonDate != value))
				{
					this._AzmoonDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoalateSahih", DbType="Int NOT NULL")]
		public int SoalateSahih
		{
			get
			{
				return this._SoalateSahih;
			}
			set
			{
				if ((this._SoalateSahih != value))
				{
					this._SoalateSahih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoalateEshtebah", DbType="Int NOT NULL")]
		public int SoalateEshtebah
		{
			get
			{
				return this._SoalateEshtebah;
			}
			set
			{
				if ((this._SoalateEshtebah != value))
				{
					this._SoalateEshtebah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedooneJavab", DbType="Int NOT NULL")]
		public int BedooneJavab
		{
			get
			{
				return this._BedooneJavab;
			}
			set
			{
				if ((this._BedooneJavab != value))
				{
					this._BedooneJavab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMark", DbType="Float NOT NULL")]
		public double TotalMark
		{
			get
			{
				return this._TotalMark;
			}
			set
			{
				if ((this._TotalMark != value))
				{
					this._TotalMark = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xtblDropUsers")]
	public partial class xtblDropUser
	{
		
		private decimal _UsersID;
		
		private string _NameSname;
		
		private string _UserNAme;
		
		public xtblDropUser()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersID", DbType="Decimal(18,0) NOT NULL")]
		public decimal UsersID
		{
			get
			{
				return this._UsersID;
			}
			set
			{
				if ((this._UsersID != value))
				{
					this._UsersID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameSname", DbType="NVarChar(715) NOT NULL", CanBeNull=false)]
		public string NameSname
		{
			get
			{
				return this._NameSname;
			}
			set
			{
				if ((this._NameSname != value))
				{
					this._NameSname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNAme", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserNAme
		{
			get
			{
				return this._UserNAme;
			}
			set
			{
				if ((this._UserNAme != value))
				{
					this._UserNAme = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xtblKarname")]
	public partial class xtblKarname
	{
		
		private string _UserNAme;
		
		private string _Expr1;
		
		private string _AzmoonTitle;
		
		private string _AzmoonDate;
		
		private int _SoalateSahih;
		
		private int _SoalateEshtebah;
		
		private int _BedooneJavab;
		
		private double _TotalMark;
		
		public xtblKarname()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNAme", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserNAme
		{
			get
			{
				return this._UserNAme;
			}
			set
			{
				if ((this._UserNAme != value))
				{
					this._UserNAme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AzmoonTitle
		{
			get
			{
				return this._AzmoonTitle;
			}
			set
			{
				if ((this._AzmoonTitle != value))
				{
					this._AzmoonTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AzmoonDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AzmoonDate
		{
			get
			{
				return this._AzmoonDate;
			}
			set
			{
				if ((this._AzmoonDate != value))
				{
					this._AzmoonDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoalateSahih", DbType="Int NOT NULL")]
		public int SoalateSahih
		{
			get
			{
				return this._SoalateSahih;
			}
			set
			{
				if ((this._SoalateSahih != value))
				{
					this._SoalateSahih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoalateEshtebah", DbType="Int NOT NULL")]
		public int SoalateEshtebah
		{
			get
			{
				return this._SoalateEshtebah;
			}
			set
			{
				if ((this._SoalateEshtebah != value))
				{
					this._SoalateEshtebah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedooneJavab", DbType="Int NOT NULL")]
		public int BedooneJavab
		{
			get
			{
				return this._BedooneJavab;
			}
			set
			{
				if ((this._BedooneJavab != value))
				{
					this._BedooneJavab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMark", DbType="Float NOT NULL")]
		public double TotalMark
		{
			get
			{
				return this._TotalMark;
			}
			set
			{
				if ((this._TotalMark != value))
				{
					this._TotalMark = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xtblAvgKarname")]
	public partial class xtblAvgKarname
	{
		
		private string _UserNAme;
		
		private string _Expr1;
		
		private System.Nullable<double> _Expr2;
		
		public xtblAvgKarname()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNAme", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserNAme
		{
			get
			{
				return this._UserNAme;
			}
			set
			{
				if ((this._UserNAme != value))
				{
					this._UserNAme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr2", DbType="Float")]
		public System.Nullable<double> Expr2
		{
			get
			{
				return this._Expr2;
			}
			set
			{
				if ((this._Expr2 != value))
				{
					this._Expr2 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
